//For SearchField
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

//For Api Call
export const REQUEST_POKEMON_PENDING = 'REQUEST_POKEMON_PENDING';
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS';
export const REQUEST_POKEMON_FAILED = 'REQUEST_POKEMON_FAILED';
